mbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  right_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_motor
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_motor
    pid: {p: 100.0, i: 0.01, d: 10.0}