controller_freqeuncy: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:  
  max_vel_x: 0.15
  min_vel_x: 0.05
  max_vel_y: 0
  min_vel_y: 0

  max_vel_theta: 0.4
  min_in_place_vel_theta: 0.1

  escape_vel: -0.1

  acc_lim_theta: 3.5
  acc_lim_x: 2.5
  acc_lim_y: 0
  
  yaw_goal_tolerance: 1.0
  xy_goal_tolerance: 1.0

  pdist_scale: 0.8
  occdist_scale: 0.4

  holonomic_robot: false
  meter_scoring: true

  dwa: true
  simple_attractor: false

  prune_plan: true