TrajectoryPlannerROS:
  controller_freqeuncy: 3.0
  max_vel_x: 0.3
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2

  escape_vel: -0.1

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0
  
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1

  pdist_scale: 0.8
  occdist_scale: 0.4

  holonomic_robot: false
  meter_scoring: true