TrajectoryPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_theta: 3.5
  max_vel_x: 0.25
  min_vel_x: 0.05
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.2
  escape_vel: -0.1
  holonomic_robot: false
  y_vels: [-0.3, -0.1, 0.1, 0.3] 
  # Goal tolerance parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 1.0
  latch_xy_goal_tolerance: true
  # Forward simulation parameters
  sim_time: 1
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 20
  # Trajectory scoring parameters
  meter_scoring: false
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: false
  dwa: true
  publish_cost_grid_pc: false
  global_frame_id: odom
  # Oscillation prevention parameters
  oscillation_reset_dist: 0.05
  # Global plan parameters
  prune_plan: true