obstacle_range: 3
raytrace_range: 3
robot_radius: 0.203
inflation_radius: 0.02
observation_sources: laser_scan_sensor
laser_scan_sensor: 
  sensor_frame: laser_sensor
  data_type: LaserScan
  topic: /mbot/laser/scan
  marking: true 
  clearing: true
  expected_update_rate: 0.5
  inf_is_valid: true