robot_radius: 0.203

static_layer:
  enabled: true
  map_topic: /map

obstacle_layer:
  # Global filtering parameters
  enabled: true
  max_obstacle_height: 2.0
  obstacle_range: 6.0
  raytrace_range: 6.0
  # Sensor management parameters
  observation_sources: laser_scan_sensor
  laser_scan_sensor: 
    data_type: LaserScan
    topic: /mbot/laser/scan
    marking: true
    clearing: true
    expected_update_rate: 0
  # Obstacle costmap plugin
  track_unknown_space: true
  footprint_clearing_enable: true
  combination_method: 0

inflation_layer:
  enabled: true
  inflation_radius: 0.28
  cost_scaling_factor: 5.0
