global_costmap:
  global_frame: /map
  robot_base_frame: base_footprint  
  update_frequency: 3.0
  publish_frequency: 0
  static_map: true
  rolling_window: false
  transform_tolerance: 1.0
  resolution: 0.05
  map_type: costmap