local_costmap:
  global_frame: /odom
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 3.0
  resolution: 0.05
  map_type: costmap